/* CSS */
import './css/TermsStyles.css';

/* COMPONENTS */
import BackgroundDecor from '../../components/backgroundDecor';

/* REACT ICONS */
import { IoShieldOutline, IoDocumentTextOutline } from 'react-icons/io5';

/* REACT */
import { useState } from 'react';

export default function Terms() {
  const [content, setContent] = useState('terms');

  const handleClick = (event) => {
    event.target.classList.forEach((name) => {
      if (name.includes('terms_option_active')) return;
      document.querySelectorAll('.terms_li').forEach((active) => {
        if (active.classList.contains('terms_option_active')) {
          active.classList.remove('terms_option_active');
        }
      });
      setContent(event.currentTarget.dataset.name);
      event.target.classList.add('terms_option_active');
    });
  };

  return (
    <div id="terms_div_container">
      <BackgroundDecor />

      <h1>Termos e Políticas</h1>
      <p>Informações legais e políticas do Tomas.</p>

      <div id="terms_div_navigation_container">
        <div id="terms_div_nagigation">
          <ul>
            <li
              className="terms_li terms_option_active"
              data-name="terms"
              onClick={(e) => handleClick(e)}
            >
              <IoDocumentTextOutline /> Termos de Uso
            </li>
            <li
              className="terms_li"
              data-name="privacy"
              onClick={(e) => handleClick(e)}
            >
              <IoShieldOutline /> Política de Privacidade
            </li>
          </ul>
        </div>
      </div>

      <div id="terms_div_content">
        <h3>
          {content === 'terms' ? 'Termos de Uso' : 'Política de Privacidade'}
        </h3>
        <p>{content === 'terms' ? getTerms() : getPrivacy()}</p>
      </div>
    </div>
  );
}

function getTerms() {
  return `
    termos do thomas.... Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium expedita ut placeat eaque dolor sint harum commodi? Saepe, recusandae ad fugit autem in perferendis eligendi, molestiae perspiciatis, optio facilis assumenda?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut animi quia voluptatibus consequatur libero, blanditiis a. Optio, quam ea ullam odio rerum, tempore vel, debitis exercitationem sit repudiandae illo iusto?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam adipisci magni atque est. Tempora fugiat quidem ea enim molestiae, quod porro asperiores explicabo illum, ad corrupti illo odio? Nam, odit! Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure eos eveniet ab rerum earum? Reiciendis ducimus ex facere exercitationem delectus sint itaque ea aliquam voluptate, laboriosam minima fugiat quo praesentium!termos do thomas.... Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium expedita ut placeat eaque dolor sint harum commodi? Saepe, recusandae ad fugit autem in perferendis eligendi, molestiae perspiciatis, optio facilis assumenda?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut animi quia voluptatibus consequatur libero, blanditiis a. Optio, quam ea ullam odio rerum, tempore vel, debitis exercitationem sit repudiandae illo iusto?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam adipisci magni atque est. Tempora fugiat quidem ea enim molestiae, quod porro asperiores explicabo illum, ad corrupti illo odio? Nam, odit! Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure eos eveniet ab rerum earum? Reiciendis ducimus ex facere exercitationem delectus sint itaque ea aliquam voluptate, laboriosam minima fugiat quo praesentium!termos do thomas.... Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium expedita ut placeat eaque dolor sint harum commodi? Saepe, recusandae ad fugit autem in perferendis eligendi, molestiae perspiciatis, optio facilis assumenda?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut animi quia voluptatibus consequatur libero, blanditiis a. Optio, quam ea ullam odio rerum, tempore vel, debitis exercitationem sit repudiandae illo iusto?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam adipisci magni atque est. Tempora fugiat quidem ea enim molestiae, quod porro asperiores explicabo illum, ad corrupti illo odio? Nam, odit! Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure eos eveniet ab rerum earum? Reiciendis ducimus ex facere exercitationem delectus sint itaque ea aliquam voluptate, laboriosam minima fugiat quo praesentium!termos do thomas.... Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium expedita ut placeat eaque dolor sint harum commodi? Saepe, recusandae ad fugit autem in perferendis eligendi, molestiae perspiciatis, optio facilis assumenda?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut animi quia voluptatibus consequatur libero, blanditiis a. Optio, quam ea ullam odio rerum, tempore vel, debitis exercitationem sit repudiandae illo iusto?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam adipisci magni atque est. Tempora fugiat quidem ea enim molestiae, quod porro asperiores explicabo illum, ad corrupti illo odio? Nam, odit! Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure eos eveniet ab rerum earum? Reiciendis ducimus ex facere exercitationem delectus sint itaque ea aliquam voluptate, laboriosam minima fugiat quo praesentium!termos do thomas.... Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium expedita ut placeat eaque dolor sint harum commodi? Saepe, recusandae ad fugit autem in perferendis eligendi, molestiae perspiciatis, optio facilis assumenda?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut animi quia voluptatibus consequatur libero, blanditiis a. Optio, quam ea ullam odio rerum, tempore vel, debitis exercitationem sit repudiandae illo iusto?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam adipisci magni atque est. Tempora fugiat quidem ea enim molestiae, quod porro asperiores explicabo illum, ad corrupti illo odio? Nam, odit! Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure eos eveniet ab rerum earum? Reiciendis ducimus ex facere exercitationem delectus sint itaque ea aliquam voluptate, laboriosam minima fugiat quo praesentium!termos do thomas.... Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium expedita ut placeat eaque dolor sint harum commodi? Saepe, recusandae ad fugit autem in perferendis eligendi, molestiae perspiciatis, optio facilis assumenda?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut animi quia voluptatibus consequatur libero, blanditiis a. Optio, quam ea ullam odio rerum, tempore vel, debitis exercitationem sit repudiandae illo iusto?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam adipisci magni atque est. Tempora fugiat quidem ea enim molestiae, quod porro asperiores explicabo illum, ad corrupti illo odio? Nam, odit! Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure eos eveniet ab rerum earum? Reiciendis ducimus ex facere exercitationem delectus sint itaque ea aliquam voluptate, laboriosam minima fugiat quo praesentium!termos do thomas.... Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium expedita ut placeat eaque dolor sint harum commodi? Saepe, recusandae ad fugit autem in perferendis eligendi, molestiae perspiciatis, optio facilis assumenda?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut animi quia voluptatibus consequatur libero, blanditiis a. Optio, quam ea ullam odio rerum, tempore vel, debitis exercitationem sit repudiandae illo iusto?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam adipisci magni atque est. Tempora fugiat quidem ea enim molestiae, quod porro asperiores explicabo illum, ad corrupti illo odio? Nam, odit! Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure eos eveniet ab rerum earum? Reiciendis ducimus ex facere exercitationem delectus sint itaque ea aliquam voluptate, laboriosam minima fugiat quo praesentium!termos do thomas.... Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium expedita ut placeat eaque dolor sint harum commodi? Saepe, recusandae ad fugit autem in perferendis eligendi, molestiae perspiciatis, optio facilis assumenda?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut animi quia voluptatibus consequatur libero, blanditiis a. Optio, quam ea ullam odio rerum, tempore vel, debitis exercitationem sit repudiandae illo iusto?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam adipisci magni atque est. Tempora fugiat quidem ea enim molestiae, quod porro asperiores explicabo illum, ad corrupti illo odio? Nam, odit! Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure eos eveniet ab rerum earum? Reiciendis ducimus ex facere exercitationem delectus sint itaque ea aliquam voluptate, laboriosam minima fugiat quo praesentium!termos do thomas.... Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium expedita ut placeat eaque dolor sint harum commodi? Saepe, recusandae ad fugit autem in perferendis eligendi, molestiae perspiciatis, optio facilis assumenda?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut animi quia voluptatibus consequatur libero, blanditiis a. Optio, quam ea ullam odio rerum, tempore vel, debitis exercitationem sit repudiandae illo iusto?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam adipisci magni atque est. Tempora fugiat quidem ea enim molestiae, quod porro asperiores explicabo illum, ad corrupti illo odio? Nam, odit! Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure eos eveniet ab rerum earum? Reiciendis ducimus ex facere exercitationem delectus sint itaque ea aliquam voluptate, laboriosam minima fugiat quo praesentium!termos do thomas.... Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium expedita ut placeat eaque dolor sint harum commodi? Saepe, recusandae ad fugit autem in perferendis eligendi, molestiae perspiciatis, optio facilis assumenda?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut animi quia voluptatibus consequatur libero, blanditiis a. Optio, quam ea ullam odio rerum, tempore vel, debitis exercitationem sit repudiandae illo iusto?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam adipisci magni atque est. Tempora fugiat quidem ea enim molestiae, quod porro asperiores explicabo illum, ad corrupti illo odio? Nam, odit! Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure eos eveniet ab rerum earum? Reiciendis ducimus ex facere exercitationem delectus sint itaque ea aliquam voluptate, laboriosam minima fugiat quo praesentium!termos do thomas.... Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium expedita ut placeat eaque dolor sint harum commodi? Saepe, recusandae ad fugit autem in perferendis eligendi, molestiae perspiciatis, optio facilis assumenda?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut animi quia voluptatibus consequatur libero, blanditiis a. Optio, quam ea ullam odio rerum, tempore vel, debitis exercitationem sit repudiandae illo iusto?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam adipisci magni atque est. Tempora fugiat quidem ea enim molestiae, quod porro asperiores explicabo illum, ad corrupti illo odio? Nam, odit! Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure eos eveniet ab rerum earum? Reiciendis ducimus ex facere exercitationem delectus sint itaque ea aliquam voluptate, laboriosam minima fugiat quo praesentium!termos do thomas.... Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium expedita ut placeat eaque dolor sint harum commodi? Saepe, recusandae ad fugit autem in perferendis eligendi, molestiae perspiciatis, optio facilis assumenda?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut animi quia voluptatibus consequatur libero, blanditiis a. Optio, quam ea ullam odio rerum, tempore vel, debitis exercitationem sit repudiandae illo iusto?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam adipisci magni atque est. Tempora fugiat quidem ea enim molestiae, quod porro asperiores explicabo illum, ad corrupti illo odio? Nam, odit! Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure eos eveniet ab rerum earum? Reiciendis ducimus ex facere exercitationem delectus sint itaque ea aliquam voluptate, laboriosam minima fugiat quo praesentium!termos do thomas.... Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium expedita ut placeat eaque dolor sint harum commodi? Saepe, recusandae ad fugit autem in perferendis eligendi, molestiae perspiciatis, optio facilis assumenda?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut animi quia voluptatibus consequatur libero, blanditiis a. Optio, quam ea ullam odio rerum, tempore vel, debitis exercitationem sit repudiandae illo iusto?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam adipisci magni atque est. Tempora fugiat quidem ea enim molestiae, quod porro asperiores explicabo illum, ad corrupti illo odio? Nam, odit! Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure eos eveniet ab rerum earum? Reiciendis ducimus ex facere exercitationem delectus sint itaque ea aliquam voluptate, laboriosam minima fugiat quo praesentium!termos do thomas.... Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium expedita ut placeat eaque dolor sint harum commodi? Saepe, recusandae ad fugit autem in perferendis eligendi, molestiae perspiciatis, optio facilis assumenda?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut animi quia voluptatibus consequatur libero, blanditiis a. Optio, quam ea ullam odio rerum, tempore vel, debitis exercitationem sit repudiandae illo iusto?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam adipisci magni atque est. Tempora fugiat quidem ea enim molestiae, quod porro asperiores explicabo illum, ad corrupti illo odio? Nam, odit! Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure eos eveniet ab rerum earum? Reiciendis ducimus ex facere exercitationem delectus sint itaque ea aliquam voluptate, laboriosam minima fugiat quo praesentium!termos do thomas.... Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium expedita ut placeat eaque dolor sint harum commodi? Saepe, recusandae ad fugit autem in perferendis eligendi, molestiae perspiciatis, optio facilis assumenda?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut animi quia voluptatibus consequatur libero, blanditiis a. Optio, quam ea ullam odio rerum, tempore vel, debitis exercitationem sit repudiandae illo iusto?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam adipisci magni atque est. Tempora fugiat quidem ea enim molestiae, quod porro asperiores explicabo illum, ad corrupti illo odio? Nam, odit! Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure eos eveniet ab rerum earum? Reiciendis ducimus ex facere exercitationem delectus sint itaque ea aliquam voluptate, laboriosam minima fugiat quo praesentium!termos do thomas.... Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium expedita ut placeat eaque dolor sint harum commodi? Saepe, recusandae ad fugit autem in perferendis eligendi, molestiae perspiciatis, optio facilis assumenda?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut animi quia voluptatibus consequatur libero, blanditiis a. Optio, quam ea ullam odio rerum, tempore vel, debitis exercitationem sit repudiandae illo iusto?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam adipisci magni atque est. Tempora fugiat quidem ea enim molestiae, quod porro asperiores explicabo illum, ad corrupti illo odio? Nam, odit! Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure eos eveniet ab rerum earum? Reiciendis ducimus ex facere exercitationem delectus sint itaque ea aliquam voluptate, laboriosam minima fugiat quo praesentium!termos do thomas.... Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium expedita ut placeat eaque dolor sint harum commodi? Saepe, recusandae ad fugit autem in perferendis eligendi, molestiae perspiciatis, optio facilis assumenda?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut animi quia voluptatibus consequatur libero, blanditiis a. Optio, quam ea ullam odio rerum, tempore vel, debitis exercitationem sit repudiandae illo iusto?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam adipisci magni atque est. Tempora fugiat quidem ea enim molestiae, quod porro asperiores explicabo illum, ad corrupti illo odio? Nam, odit! Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure eos eveniet ab rerum earum? Reiciendis ducimus ex facere exercitationem delectus sint itaque ea aliquam voluptate, laboriosam minima fugiat quo praesentium!
    `;
}

function getPrivacy() {
  return `
    politica do thomas.... Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium expedita ut placeat eaque dolor sint harum commodi? Saepe, recusandae ad fugit autem in perferendis eligendi, molestiae perspiciatis, optio facilis assumenda?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut animi quia voluptatibus consequatur libero, blanditiis a. Optio, quam ea ullam odio rerum, tempore vel, debitis exercitationem sit repudiandae illo iusto?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam adipisci magni atque est. Tempora fugiat quidem ea enim molestiae, quod porro asperiores explicabo illum, ad corrupti illo odio? Nam, odit! Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure eos eveniet ab rerum earum? Reiciendis ducimus ex facere exercitationem delectus sint itaque ea aliquam voluptate, laboriosam minima fugiat quo praesentium!termos do thomas.... Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium expedita ut placeat eaque dolor sint harum commodi? Saepe, recusandae ad fugit autem in perferendis eligendi, molestiae perspiciatis, optio facilis assumenda?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut animi quia voluptatibus consequatur libero, blanditiis a. Optio, quam ea ullam odio rerum, tempore vel, debitis exercitationem sit repudiandae illo iusto?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam adipisci magni atque est. Tempora fugiat quidem ea enim molestiae, quod porro asperiores explicabo illum, ad corrupti illo odio? Nam, odit! Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure eos eveniet ab rerum earum? Reiciendis ducimus ex facere exercitationem delectus sint itaque ea aliquam voluptate, laboriosam minima fugiat quo praesentium!termos do thomas.... Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium expedita ut placeat eaque dolor sint harum commodi? Saepe, recusandae ad fugit autem in perferendis eligendi, molestiae perspiciatis, optio facilis assumenda?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut animi quia voluptatibus consequatur libero, blanditiis a. Optio, quam ea ullam odio rerum, tempore vel, debitis exercitationem sit repudiandae illo iusto?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam adipisci magni atque est. Tempora fugiat quidem ea enim molestiae, quod porro asperiores explicabo illum, ad corrupti illo odio? Nam, odit! Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure eos eveniet ab rerum earum? Reiciendis ducimus ex facere exercitationem delectus sint itaque ea aliquam voluptate, laboriosam minima fugiat quo praesentium!termos do thomas.... Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium expedita ut placeat eaque dolor sint harum commodi? Saepe, recusandae ad fugit autem in perferendis eligendi, molestiae perspiciatis, optio facilis assumenda?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut animi quia voluptatibus consequatur libero, blanditiis a. Optio, quam ea ullam odio rerum, tempore vel, debitis exercitationem sit repudiandae illo iusto?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam adipisci magni atque est. Tempora fugiat quidem ea enim molestiae, quod porro asperiores explicabo illum, ad corrupti illo odio? Nam, odit! Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure eos eveniet ab rerum earum? Reiciendis ducimus ex facere exercitationem delectus sint itaque ea aliquam voluptate, laboriosam minima fugiat quo praesentium!termos do thomas.... Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium expedita ut placeat eaque dolor sint harum commodi? Saepe, recusandae ad fugit autem in perferendis eligendi, molestiae perspiciatis, optio facilis assumenda?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut animi quia voluptatibus consequatur libero, blanditiis a. Optio, quam ea ullam odio rerum, tempore vel, debitis exercitationem sit repudiandae illo iusto?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam adipisci magni atque est. Tempora fugiat quidem ea enim molestiae, quod porro asperiores explicabo illum, ad corrupti illo odio? Nam, odit! Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure eos eveniet ab rerum earum? Reiciendis ducimus ex facere exercitationem delectus sint itaque ea aliquam voluptate, laboriosam minima fugiat quo praesentium!termos do thomas.... Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium expedita ut placeat eaque dolor sint harum commodi? Saepe, recusandae ad fugit autem in perferendis eligendi, molestiae perspiciatis, optio facilis assumenda?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut animi quia voluptatibus consequatur libero, blanditiis a. Optio, quam ea ullam odio rerum, tempore vel, debitis exercitationem sit repudiandae illo iusto?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam adipisci magni atque est. Tempora fugiat quidem ea enim molestiae, quod porro asperiores explicabo illum, ad corrupti illo odio? Nam, odit! Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure eos eveniet ab rerum earum? Reiciendis ducimus ex facere exercitationem delectus sint itaque ea aliquam voluptate, laboriosam minima fugiat quo praesentium!termos do thomas.... Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium expedita ut placeat eaque dolor sint harum commodi? Saepe, recusandae ad fugit autem in perferendis eligendi, molestiae perspiciatis, optio facilis assumenda?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut animi quia voluptatibus consequatur libero, blanditiis a. Optio, quam ea ullam odio rerum, tempore vel, debitis exercitationem sit repudiandae illo iusto?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam adipisci magni atque est. Tempora fugiat quidem ea enim molestiae, quod porro asperiores explicabo illum, ad corrupti illo odio? Nam, odit! Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure eos eveniet ab rerum earum? Reiciendis ducimus ex facere exercitationem delectus sint itaque ea aliquam voluptate, laboriosam minima fugiat quo praesentium!termos do thomas.... Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium expedita ut placeat eaque dolor sint harum commodi? Saepe, recusandae ad fugit autem in perferendis eligendi, molestiae perspiciatis, optio facilis assumenda?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut animi quia voluptatibus consequatur libero, blanditiis a. Optio, quam ea ullam odio rerum, tempore vel, debitis exercitationem sit repudiandae illo iusto?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam adipisci magni atque est. Tempora fugiat quidem ea enim molestiae, quod porro asperiores explicabo illum, ad corrupti illo odio? Nam, odit! Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure eos eveniet ab rerum earum? Reiciendis ducimus ex facere exercitationem delectus sint itaque ea aliquam voluptate, laboriosam minima fugiat quo praesentium!termos do thomas.... Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium expedita ut placeat eaque dolor sint harum commodi? Saepe, recusandae ad fugit autem in perferendis eligendi, molestiae perspiciatis, optio facilis assumenda?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut animi quia voluptatibus consequatur libero, blanditiis a. Optio, quam ea ullam odio rerum, tempore vel, debitis exercitationem sit repudiandae illo iusto?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam adipisci magni atque est. Tempora fugiat quidem ea enim molestiae, quod porro asperiores explicabo illum, ad corrupti illo odio? Nam, odit! Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure eos eveniet ab rerum earum? Reiciendis ducimus ex facere exercitationem delectus sint itaque ea aliquam voluptate, laboriosam minima fugiat quo praesentium!termos do thomas.... Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium expedita ut placeat eaque dolor sint harum commodi? Saepe, recusandae ad fugit autem in perferendis eligendi, molestiae perspiciatis, optio facilis assumenda?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut animi quia voluptatibus consequatur libero, blanditiis a. Optio, quam ea ullam odio rerum, tempore vel, debitis exercitationem sit repudiandae illo iusto?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam adipisci magni atque est. Tempora fugiat quidem ea enim molestiae, quod porro asperiores explicabo illum, ad corrupti illo odio? Nam, odit! Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure eos eveniet ab rerum earum? Reiciendis ducimus ex facere exercitationem delectus sint itaque ea aliquam voluptate, laboriosam minima fugiat quo praesentium!termos do thomas.... Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium expedita ut placeat eaque dolor sint harum commodi? Saepe, recusandae ad fugit autem in perferendis eligendi, molestiae perspiciatis, optio facilis assumenda?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut animi quia voluptatibus consequatur libero, blanditiis a. Optio, quam ea ullam odio rerum, tempore vel, debitis exercitationem sit repudiandae illo iusto?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam adipisci magni atque est. Tempora fugiat quidem ea enim molestiae, quod porro asperiores explicabo illum, ad corrupti illo odio? Nam, odit! Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure eos eveniet ab rerum earum? Reiciendis ducimus ex facere exercitationem delectus sint itaque ea aliquam voluptate, laboriosam minima fugiat quo praesentium!termos do thomas.... Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium expedita ut placeat eaque dolor sint harum commodi? Saepe, recusandae ad fugit autem in perferendis eligendi, molestiae perspiciatis, optio facilis assumenda?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut animi quia voluptatibus consequatur libero, blanditiis a. Optio, quam ea ullam odio rerum, tempore vel, debitis exercitationem sit repudiandae illo iusto?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam adipisci magni atque est. Tempora fugiat quidem ea enim molestiae, quod porro asperiores explicabo illum, ad corrupti illo odio? Nam, odit! Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure eos eveniet ab rerum earum? Reiciendis ducimus ex facere exercitationem delectus sint itaque ea aliquam voluptate, laboriosam minima fugiat quo praesentium!termos do thomas.... Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium expedita ut placeat eaque dolor sint harum commodi? Saepe, recusandae ad fugit autem in perferendis eligendi, molestiae perspiciatis, optio facilis assumenda?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut animi quia voluptatibus consequatur libero, blanditiis a. Optio, quam ea ullam odio rerum, tempore vel, debitis exercitationem sit repudiandae illo iusto?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam adipisci magni atque est. Tempora fugiat quidem ea enim molestiae, quod porro asperiores explicabo illum, ad corrupti illo odio? Nam, odit! Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure eos eveniet ab rerum earum? Reiciendis ducimus ex facere exercitationem delectus sint itaque ea aliquam voluptate, laboriosam minima fugiat quo praesentium!termos do thomas.... Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium expedita ut placeat eaque dolor sint harum commodi? Saepe, recusandae ad fugit autem in perferendis eligendi, molestiae perspiciatis, optio facilis assumenda?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut animi quia voluptatibus consequatur libero, blanditiis a. Optio, quam ea ullam odio rerum, tempore vel, debitis exercitationem sit repudiandae illo iusto?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam adipisci magni atque est. Tempora fugiat quidem ea enim molestiae, quod porro asperiores explicabo illum, ad corrupti illo odio? Nam, odit! Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure eos eveniet ab rerum earum? Reiciendis ducimus ex facere exercitationem delectus sint itaque ea aliquam voluptate, laboriosam minima fugiat quo praesentium!termos do thomas.... Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium expedita ut placeat eaque dolor sint harum commodi? Saepe, recusandae ad fugit autem in perferendis eligendi, molestiae perspiciatis, optio facilis assumenda?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut animi quia voluptatibus consequatur libero, blanditiis a. Optio, quam ea ullam odio rerum, tempore vel, debitis exercitationem sit repudiandae illo iusto?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam adipisci magni atque est. Tempora fugiat quidem ea enim molestiae, quod porro asperiores explicabo illum, ad corrupti illo odio? Nam, odit! Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure eos eveniet ab rerum earum? Reiciendis ducimus ex facere exercitationem delectus sint itaque ea aliquam voluptate, laboriosam minima fugiat quo praesentium!termos do thomas.... Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium expedita ut placeat eaque dolor sint harum commodi? Saepe, recusandae ad fugit autem in perferendis eligendi, molestiae perspiciatis, optio facilis assumenda?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut animi quia voluptatibus consequatur libero, blanditiis a. Optio, quam ea ullam odio rerum, tempore vel, debitis exercitationem sit repudiandae illo iusto?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam adipisci magni atque est. Tempora fugiat quidem ea enim molestiae, quod porro asperiores explicabo illum, ad corrupti illo odio? Nam, odit! Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure eos eveniet ab rerum earum? Reiciendis ducimus ex facere exercitationem delectus sint itaque ea aliquam voluptate, laboriosam minima fugiat quo praesentium!termos do thomas.... Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium expedita ut placeat eaque dolor sint harum commodi? Saepe, recusandae ad fugit autem in perferendis eligendi, molestiae perspiciatis, optio facilis assumenda?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut animi quia voluptatibus consequatur libero, blanditiis a. Optio, quam ea ullam odio rerum, tempore vel, debitis exercitationem sit repudiandae illo iusto?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam adipisci magni atque est. Tempora fugiat quidem ea enim molestiae, quod porro asperiores explicabo illum, ad corrupti illo odio? Nam, odit! Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure eos eveniet ab rerum earum? Reiciendis ducimus ex facere exercitationem delectus sint itaque ea aliquam voluptate, laboriosam minima fugiat quo praesentium!
    
    `;
}
